Feature/complete revamp of github actions
TortugaAttack/rdf4cpp pull request #103
Opened 2022-12-01 12:48 UTC by bigerl

2022-12-01 16:41 UTC, nkaralis commented
I do not know why the coverage stopped working. I will have a look at it as soon as possible and get back to you.

2022-12-05 10:58 UTC, Clueliss requested changes
Looks good to me and seems to run fine.
One potential thingy for the deploy tests :)

2022-12-05 10:58 UTC, liss-h commented on .github/workflows/reusable_run_test_and_examples_by_linking_type.yml
> +          ctest --parallel 2
More out of interest: why specifically 2?

2022-12-05 10:58 UTC, liss-h commented on .github/workflows/test_packaging_and_deployment.yml
> +  packaging:
It could maybe makes sense to include one GCC release here as well, just in case we come across some compiler specific behaviour that specifically breaks something in packaging. Tbh I am not sure what that would be but considering the fiddly nature of the datatypes atm it probably makes sense.

2022-12-05 11:58 UTC, bigerl commented on .github/workflows/reusable_run_test_and_examples_by_linking_type.yml
> +          ctest --parallel 2
runners have two cores: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

2022-12-05 13:42 UTC, bigerl commented on .github/workflows/test_packaging_and_deployment.yml
> +  packaging:
has now builds for gcc-12 and clang-14

2022-12-05 14:02 UTC, bigerl commented
I would ignore for now the problem that github actions seem to populate reusable actions via matrices not always correctly. See https://github.com/rdf4cpp/rdf4cpp/actions/runs/3620679876/attempts/1 where we have  `clang-14, ubuntu-22.04 / test-and-examples-static / static lib` twice.

2022-12-05 15:04 UTC, Clueliss approved these changes

2022-12-05 15:27 UTC, merged