Fix: node storage literal ids assignment
TortugaAttack/rdf4cpp pull request #148
Opened 2023-02-14 11:13 UTC by Clueliss

Additional PR to complete #146

2023-02-21 08:12 UTC, Clueliss commented
Don't mind the massive amount of commits, I branched from the other PR

2023-02-21 09:16 UTC, bigerl requested changes
Thx for the PR. The patch looks good. It's a bit unfortunate that you had to replace the access by type with an access by index. Still, I think it is better to use the array here because using a tuple instead would probably prolong compilation again. 

The proposed change is only of cosmetic nature. Otherwise, the PR can be merged.

2023-02-21 09:16 UTC, bigerl commented on src/rdf4cpp/rdf/storage/node/reference_node_storage/ReferenceNodeStorageBackend.cpp
> +                    if (id >= 1ul << LiteralID::width) [[unlikely]] {
```suggestion
                    if (id >= (1ul << LiteralID::width)) [[unlikely]] {
```

for readability.

2023-02-21 09:16 UTC, bigerl commented on src/rdf4cpp/rdf/storage/node/reference_node_storage/ReferenceNodeStorageBackend.cpp
> +                        if (id >= 1ul << LiteralID::width) [[unlikely]] {
see above

2023-02-21 09:16 UTC, bigerl commented on src/rdf4cpp/rdf/storage/node/reference_node_storage/ReferenceNodeStorageBackend.cpp
> +        if (id >= 1ul << NodeID::width) [[unlikely]] {
see above

2023-02-21 09:16 UTC, bigerl commented on src/rdf4cpp/rdf/storage/node/reference_node_storage/ReferenceNodeStorageBackend.cpp
> +        if (id >= 1ul << NodeID::width) [[unlikely]] {
see above

2023-02-22 08:43 UTC, bigerl approved these changes

2023-02-22 08:44 UTC, merged