Feature/UUID
TortugaAttack/rdf4cpp pull request #149
Opened 2023-02-15 15:44 UTC by mcb5637

implementing #100

2023-02-16 15:47 UTC, Clueliss requested changes
Looks good thx :)
There is just one minor thing

2023-02-16 15:47 UTC, Clueliss commented on src/rdf4cpp/rdf/IRI.cpp
> +    std::string s = stream.str();  // unfortunately there is no string_view into a stringstream
C++20 added `std::stringstream::view`

2023-02-20 14:13 UTC, liss-h approved these changes

2023-02-20 17:22 UTC, bigerl commented
Please resolve the conflicts with develop. Then we are ready to merge

2023-02-27 10:48 UTC, merged