hash funtions
TortugaAttack/rdf4cpp pull request #156
Opened 2023-02-28 17:02 UTC by mcb5637

implementing #98 via OpenSSL

2023-03-09 16:03 UTC, bigerl commented
I've cleaned the GitHub Actions cache. The separation between different configurations was beached somehow. Should be fine again, now. 
I also revered the changes to the CMake files regarding OpenSSL. 

One build problem with gcov remains. Please investigate that locally in your local environment. Right now, gcov is run but not uploaded. So, if there is no simple solution to the just deactivate gcov in the CI.

2023-03-14 08:42 UTC, Clueliss requested changes
Thank you; again only small details to fix

2023-03-14 08:42 UTC, Clueliss commented on src/rdf4cpp/rdf/Literal.cpp
> +    if (!this->is_string_like())
This passes for `rdf:langString` and `xsd:string` but as far as I can tell these functions are only supposed to work for `xsd:string`

2023-03-14 08:42 UTC, Clueliss commented on src/rdf4cpp/rdf/Literal.hpp
> +     * @param alg OpenSSL hash algorithm identifier
A link to the options for `alg` would be nice here

2023-03-15 12:54 UTC, Clueliss approved these changes

2023-03-16 10:44 UTC, merged