Feature: faster serialization for non nformat
TortugaAttack/rdf4cpp pull request #246
Opened 2024-02-27 10:23 UTC by Clueliss

Adds additional interfaces for the purpose of increasing serialization speed in non-nformat use-cases.

2024-02-28 17:21 UTC, bigerl requested changes
Thx for the PR. Things look good from what I can see. 
One thing I noticed, though. After going through the BufWriter architecture again for this review I found it felt a bit hard to follow. I have left some suggestions for improvements. Please start with the comments in BufWriter.

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
>   * @param value the value to be serialized
update doctstring

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
>   * @param value the value to be serialized
update doctstring

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
>   * @param value the value to be serialized
update doctstring

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
> +
Is there any Writer that doesn't use BufWriterBase? Otherwise, we could also make it a requirement to use it as Base and add write_str as static method of BufWriterBase.

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
>      }
I would suggest to add a declaration of finalize() here as well and document it. Important aspect to be mentioned: It must be called only once (at least for some implementations).

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/query/Variable.cpp
> +bool Variable::serialize(void *const buffer, writer::Cursor *const cursor, writer::FlushFunc const flush) const noexcept {
update interface in hpp as well

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/Quad.hpp
> +    bool serialize_ntriples(void *buffer, writer::Cursor *cursor, writer::FlushFunc flush) const noexcept;
*const missing in the signature compared to definition

2024-02-28 17:21 UTC, bigerl commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
A genral interface thing: it is very common that a `BufWriter` is used to extract ` void *const buffer, Cursor *cursor, FlushFunc const flush`. That is enough because typically, not the full functionality is required for `write_str`. Similar interface are everywhere throughout the code. 

For the user, providing buffer,cursor,flush is cumbersome. I would suggest that we introduce a type that has that essential info as fields and is implicitly convertible from any BufWriter implementation. That way user's can just pass in their BufWriter. 

This can completely replace the overloads like
```
template<BufWriter W>
bool write_str(std::string_view str, W &w) {
    return write_str(str, &w.buffer(), &w.cursor(), &W::flush);
}
```

and allows us to only provide one simple interface like:

```
bool serialize(BufferWriterProxy w) { // ugly name I know; maybe you have a better suggestion :)
    ...
}
```

in user-facing types. it is not templated so implementation details can completely go into cpp files.

2024-02-28 17:23 UTC, Clueliss commented on src/rdf4cpp/rdf/Quad.hpp
> +    bool serialize_ntriples(void *buffer, writer::Cursor *cursor, writer::FlushFunc flush) const noexcept;
the outer most `const` does nothing on declarations

2024-02-28 18:01 UTC, Clueliss commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
> +
Every bufwriter that is not implemented here (in rdf4cpp) does not use it

2024-02-28 18:02 UTC, Clueliss commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
Users are never really supposed to use the 3 param version, it simply exists for FFI purposes, adding the proxy defeats the purpose

2024-02-28 18:04 UTC, Clueliss commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
I guess we could make it constructable from the three params as well

2024-02-28 18:04 UTC, Clueliss commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
name suggestion: `BufWriterParts`

2024-02-28 18:07 UTC, liss-h commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
>      }
If we add a decl here we will get an IDE warning on every type inheriting from this (because the implementation in the derived will hide the previous one from the base)

2024-02-29 09:11 UTC, bigerl commented on src/rdf4cpp/rdf/Quad.hpp
> +    bool serialize_ntriples(void *buffer, writer::Cursor *cursor, writer::FlushFunc flush) const noexcept;
it is compatible, yes. It's more that it makes me uneasy that the signatures are different.

2024-02-29 09:15 UTC, bigerl commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
>      }
How about CRTP for finalize as well?

2024-02-29 09:44 UTC, Clueliss commented on src/rdf4cpp/rdf/Quad.hpp
> +    bool serialize_ntriples(void *buffer, writer::Cursor *cursor, writer::FlushFunc flush) const noexcept;
Here are some arguments against using it in declarations:
1. It doesn't give the user any additional promises or any useful information at all
2. It doesn't help the compiler to optimize the code
3. It exposes an implementation detail that the users don't want to know and shouldn't know
4. It clutters the API surface with keywords that do nothing but make the function signature longer and harder to read
5. Declarations and definitions are already not symmetric in many other ways
   - `explicit` only appears in the declaration
   - `static` only appears in the declaration
   - `[[nodiscard]]` only appears in the declaration
   - `[[maybe_unused]]` only appears in defintions

2024-02-29 11:37 UTC, bigerl commented on src/rdf4cpp/rdf/Quad.hpp
> +    bool serialize_ntriples(void *buffer, writer::Cursor *cursor, writer::FlushFunc flush) const noexcept;
point 5. convinced me :)

2024-02-29 12:51 UTC, Clueliss commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
>      }
I'm not sure what you are trying to achieve, but the `BufWriter` concept already tells you that you need to implement it and that you have to call it

2024-02-29 13:49 UTC, bigerl commented on src/rdf4cpp/rdf/writer/BufWriter.hpp
>      }
OK. That's true. 
I am also not so sure I must admit. My main concern was that users are not seeing the documentation of finalize() in their IDE. But maybe a link in the class docstring of the concrete buffer Writer implementations to the BufWriter concept would do.

2024-02-29 14:49 UTC, bigerl requested changes

2024-02-29 14:49 UTC, bigerl commented on src/rdf4cpp/rdf/Node.hpp
> +    bool serialize(writer::BufWriterParts parts) const noexcept;
I would call the parameter something like writer, buf_writer, writer_p, buf_writer_parts, writer_parts. (oder: most prefered -> least preferred).
It should focus more on what a user typically passes in then what it is converted to. After all the BufWriter implementations are mostly for construction/defining behaviour and are internally not used directly.

whatever you apply, please apply it everywhere

2024-02-29 14:49 UTC, bigerl commented on src/rdf4cpp/rdf/Node.hpp
> +     * @param parts writer parts
```suggestion
     * @param writer Typically, you pass in an instance of a writer::BufWriter (Concept) instance. Any writer::BufWriter instance is implicitly convertible to writer::BufWriterParts.
```

2024-02-29 14:49 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
> -std::string to_chars_simplified(I const value) noexcept {
where did `to_chars_simplified` go?

2024-03-01 07:10 UTC, Clueliss commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
> -std::string to_chars_simplified(I const value) noexcept {
Was unused

2024-03-01 08:12 UTC, bigerl approved these changes

2024-03-01 08:14 UTC, merged