Fix: some literal ops
TortugaAttack/rdf4cpp pull request #253
Opened 2024-03-12 14:00 UTC by Clueliss

Fixes some bugs introduced by #239

2024-03-13 08:18 UTC, Clueliss commented
Coverage still broken, ignore

2024-03-14 14:01 UTC, bigerl requested changes
thx for the PR. Now, the tests should actually tell if things are wrong. 

I am against the change though that stores xsd:hexBinary as BigEndian. I explain my considerations in a comment below.

2024-03-14 14:01 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/xsd/HexBinary.cpp
> +        // handle first byte that was not represented by two digits (if there is one)
```suggestion
        // handle the case where the most significant byte is represented by only one digit
```

2024-03-14 14:01 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/xsd/HexBinary.hpp
I think we should keep the internal representation equal between base64Binary and hexBinary. Both share the value space definition:
> The [·value space·](https://www.w3.org/TR/xmlschema-2/#dt-value-space) of base64Binary/hexBinary is the set of finite-length sequences of binary octets.

It does not specify if the octets store at position 0 LSB or MSB and it does not specify if the sequence goes from LS octet to MS octet or the other way around. 

I think though, that for the sake of keeping the interface easy to understand we should stick with little-endian for access and internal representation. So LS octet first and within the octet LSB is at position 0. Thin includes constructors and access functions.

I expect that we will use HexBinaries (or derived types) to store blobs like files in the future. There it would also be rather unusual to read hexBinary back-to-front.

2024-03-14 14:01 UTC, bigerl commented on src/rdf4cpp/rdf/Literal.cpp
> +                    auto const *entry = datatypes::registry::DatatypeRegistry::get_entry(this->datatype_id());
good catch

2024-03-14 14:01 UTC, bigerl commented on src/rdf4cpp/rdf/Literal.cpp
> +                }
what is the else branch for? Compiler warning? If so, please add a comment.

2024-03-14 14:01 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
> +        return std::signbit(value) ? writer::write_str("-0", writer) : writer::write_str("0", writer);
oops

2024-03-14 14:03 UTC, Clueliss commented on src/rdf4cpp/rdf/datatypes/xsd/HexBinary.hpp
So what's the plan for the literal hash functions then? Should I just reimplements the same thing?

2024-03-15 07:44 UTC, Clueliss commented on src/rdf4cpp/rdf/datatypes/xsd/HexBinary.hpp
Found a solution. It makes for a little awkward interface but works

2024-03-15 07:48 UTC, Clueliss commented on src/rdf4cpp/rdf/datatypes/registry/util/CharConvExt.hpp
> +        return std::signbit(value) ? writer::write_str("-0", writer) : writer::write_str("0", writer);
yeah, implicit conversions are great..

2024-03-15 12:27 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/xsd/HexBinary.hpp
I like the interface very much as it is now. Especially, the explicit `serialize_hash` for the hash algorithms.

2024-03-15 12:27 UTC, bigerl approved these changes
Looks good. thx :)

2024-03-18 06:53 UTC, merged