datatype parsing error
TortugaAttack/rdf4cpp pull request #277
Opened 2024-05-24 14:02 UTC by mcb5637

close #267 
also renamed `rdf4cpp::ParsingError` to `rdf4cpp:InvalidNode`, because it might get confused with  `rdf4cpp::parser::ParsingError`.

2024-05-27 06:36 UTC, Clueliss requested changes
Thanks for the PR, I have two general points:

1. I think it makes sense to seperate the parsing error and this one. I was just thinking if it makes sense to still somehow make them related, or maybe add a general error type to rdf4cpp that all others must inherit from (so that users can just catch `rdf4cpp::Error` and it will catch everything from rdf4cpp. Opionion or other ideas?

2. In the parser, we should probably now catch `InvalidNode` instead of `runtime_error` on node construction.

2024-05-27 06:36 UTC, Clueliss commented on src/rdf4cpp/BigDecimal.hpp
> +     * @throw ParsingError if a invalid char is found, or on exceeding the types numeric limits
InvalidNode

2024-05-27 06:36 UTC, Clueliss commented on src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp
> + * @throws ParsingError if the string cannot be parsed
InvalidNode

2024-05-27 06:36 UTC, Clueliss commented on src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp
> + * @throws ParsingError if the string cannot be parsed
InvalidNode

2024-05-27 06:36 UTC, Clueliss commented on src/rdf4cpp/datatypes/owl/Real.cpp
> +        throw InvalidNode{std::string{"owl:real parsing error:"} + e.what()};
missing space after `[..] error:`

2024-05-27 06:36 UTC, Clueliss commented on src/rdf4cpp/datatypes/owl/Rational.cpp
> +        throw InvalidNode{std::string{"owl:rational parsing error:"} + e.what()};
missing space after `[..] error:`

2024-05-27 06:36 UTC, Clueliss commented on src/rdf4cpp/InvalidNode.hpp
> +        explicit inline InvalidNode(std::string const &msg)
`inline` is implicit (because def is in struct)

2024-06-03 08:00 UTC, Clueliss requested changes
You didn't address the first review fully, see header comment

2024-06-07 11:47 UTC, mcb5637 commented
Using a common base class for InvalidNode and ParsingError might not be the best idea, because ParsingError does not inherit from std::exception and is not thrown.

2024-06-18 12:22 UTC, Clueliss commented
> Using a common base class for InvalidNode and ParsingError might not be the best idea, because ParsingError does not inherit from std::exception and is not thrown.

good point

2024-06-18 12:23 UTC, merged