improved parsing error messages
TortugaAttack/rdf4cpp pull request #289
Opened 2024-07-08 12:00 UTC by mcb5637

close #204

2024-07-16 08:28 UTC, Clueliss requested changes
Thanks
Apart from some formatting things that we might as well fix now, I have nothing to complain (I've not marked all of them, you can just look at the diff to find more of them).

The changes should make the error messages quite a bit better

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp
> +            else {
formatting

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp
> +        else if (res.ec == std::errc::result_out_of_range) {
formatting

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/time/Time.cpp
> +            throw InvalidNode(std::format("{} parsing error: minutes out of range", identifier));
curly braces

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/time/DayTimeDuration.cpp
> +            throw InvalidNode{std::format("{} parsing error: duration missing T", identifier)};
curly braces

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/time/DayTimeDuration.cpp
> +        throw InvalidNode{std::format("{} parsing error: duration missing P", identifier)};
curly braces

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/time/DateTimeStamp.cpp
> +                throw InvalidNode(std::format("{} parsing error: {:%Y-%m-%d} is invalid", identifier, date));
curly braces

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/time/DateTimeStamp.cpp
> +            throw InvalidNode(std::format("{} parsing error: seconds out of range", identifier));
curly braces

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp
> +            }
add newline after this

2024-07-16 08:28 UTC, Clueliss commented on src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp
> +    std::from_chars_result res = [&]() {
noexcept

2024-07-22 11:45 UTC, liss-h commented
Converting to draft until you've looked into the decimal stuff

2024-07-22 13:13 UTC, mcb5637 commented
concidering the time that would be needed for more precise error messages, the existing boost messages with added datatype are good enough. result is something like this: `xsd:integer parsing error: Unexpected character encountered in input.` (for any non numeric char in the input)

2024-07-23 06:28 UTC, Clueliss requested changes
A more general comment: I think it would look more "professional" if the error messages were consistent with respect to how datatypes are called. Currently there seem to be both short form (`xsd:xyz`) and full iri `http://...#xyz`. I think it would be best to choose and stick to one of them (iri probably makes things easier)

2024-07-24 14:55 UTC, Clueliss requested changes
There are a few places where you could have used the `identifier` as far as I can tell, but didn't. Idk if I missed something but if not please fix those

2024-07-24 14:55 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/integers/non_negative/NonNegativeInteger.cpp
> +        throw InvalidNode{std::string{"http://www.w3.org/2001/XMLSchema#nonNegativeInteger parsing error: "} + e.what()};
why not use the `identifier`?

2024-07-24 14:55 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/integers/non_negative/PositiveInteger.cpp
> +        throw InvalidNode{std::string{"http://www.w3.org/2001/XMLSchema#positiveInteger parsing error: "} + e.what()};
same here

2024-07-24 14:55 UTC, Clueliss commented on src/rdf4cpp/datatypes/owl/Rational.cpp
> +        throw InvalidNode{"http://www.w3.org/2002/07/owl#rational parsing error: invalid sign position"};
same here

2024-07-24 14:55 UTC, Clueliss commented on src/rdf4cpp/datatypes/owl/Real.cpp
> +        throw InvalidNode{std::string{"http://www.w3.org/2002/07/owl#real parsing error: "} + e.what()};
same here

2024-07-24 14:55 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/integers/signed/Integer.cpp
> +        throw InvalidNode{std::string{"http://www.w3.org/2001/XMLSchema#integer parsing error: "} + e.what()};
same here

2024-07-24 14:55 UTC, Clueliss commented on src/rdf4cpp/datatypes/xsd/integers/non_positive/NonPositiveInteger.cpp
> +        throw InvalidNode{std::string{"http://www.w3.org/2001/XMLSchema#nonPositiveInteger parsing error: "} + e.what()};
same here

2024-07-25 15:39 UTC, Clueliss approved these changes

2024-07-25 15:39 UTC, merged