Fix: node comparisons
TortugaAttack/rdf4cpp pull request #312
Opened 2024-09-26 09:45 UTC by liss-h

2024-09-30 14:44 UTC, bigerl requested changes
Thx for the PR. Changes look good. I only pointed out minor things, most not even originating from the PR.

2024-09-30 14:44 UTC, bigerl commented on src/rdf4cpp/Node.cpp
>      }
I would reorder it a bit

```suggestion
    if (this->handle_ == other.handle_) {
        return std::weak_ordering::equivalent;
    }
    if (this->handle_.null() || other.handle_.null()) {
        return this->handle_.null()
            ? std::weak_ordering::less
            : std::weak_ordering::greater;
    }
```

2024-09-30 14:44 UTC, bigerl commented on tests/nodes/tests_Node.cpp
> -        CHECK(iri2 < iri1);
rename 
```
TEST_SUITE("comparisions") {
```

to
```
TEST_SUITE("comparisons") {
```

2024-09-30 14:44 UTC, bigerl commented on tests/nodes/tests_Node.cpp
>              // null <=> other (expecting null < any other a)
```suggestion
            // null <=> other (expecting null < any other literal)
```

2024-09-30 16:26 UTC, liss-h commented on src/rdf4cpp/Node.cpp
>      }
Thats very subly wrong, it does not order null nodes of different types correctly

2024-10-01 07:50 UTC, bigerl commented on src/rdf4cpp/Node.cpp
>      }
```c++
std::weak_ordering Node::order(Node const &other) const noexcept {
    // first, check for null nodes
    // "Apart from BOUND, COALESCE, NOT EXISTS and EXISTS, all functions and operators operate on RDF Terms and will produce a type error if any arguments are unbound."
    // - https://www.w3.org/TR/sparql11-query/#evaluation
    if (this->null() && other.null()) {
        return this->handle_.type() <=> other.handle_.type();
    }

    if (this->handle_ == other.handle_) {
        return std::weak_ordering::equivalent;
    }
    if (this->handle_.null() || other.handle_.null()) {
        return this->handle_.null()
            ? std::weak_ordering::less
            : std::weak_ordering::greater;
    }
```

2024-10-01 08:03 UTC, bigerl approved these changes

2024-10-01 08:30 UTC, merged