fix mac compile
TortugaAttack/rdf4cpp pull request #329
Opened 2024-11-20 14:09 UTC by mcb5637

2025-01-29 08:36 UTC, liss-h requested changes
Thx for the PR, I have some questions and suggestions

2025-01-29 08:36 UTC, liss-h commented on src/rdf4cpp/storage/reference_node_storage/detail/BiDirFlatMap.hpp
> +        if constexpr (std::same_as<uint64_t, size_t>) {
I think it would probably be better if we just used `uint64_t` instead of `size_t` for the bitmap type

2025-01-29 08:36 UTC, liss-h commented on conanfile.py
> +        self.requires("dice-hash/0.4.9@dice-group/fix-mac_compile", transitive_headers=True)
Just so we don't forget: point to release (when I've created it)

2025-01-29 08:36 UTC, liss-h commented on src/rdf4cpp/util/CharMatcher.cpp
> +#endif
This is a little confusing to me, could you explain this?

2025-02-10 10:07 UTC, mcb5637 commented on src/rdf4cpp/util/CharMatcher.cpp
> +#endif
TLDR: its an optimization i did on x86 that does not work on arm

2025-02-11 08:09 UTC, liss-h commented on src/rdf4cpp/util/CharMatcher.cpp
> +#endif
Ok, I reread the comments, this time they made sense to me

2025-02-11 09:20 UTC, liss-h commented on CMakeLists.txt
> +set(POBR_VERSION 3)  # Persisted Object Binary Representation
Don't need a POBR version bump, the change in BiDirFlatMap does nothing on relevant architectures

2025-02-11 09:21 UTC, liss-h commented on CMakeLists.txt
> +set(POBR_VERSION 3)  # Persisted Object Binary Representation
I'll revert it

2025-02-12 14:39 UTC, merged