Limited-Range Integer Number Datatypes
TortugaAttack/rdf4cpp pull request #33
Opened 2022-06-19 15:33 UTC by kaimal11

2022-06-20 09:11 UTC, bigerl commented
What is the matter with the `tests_Long` failing with all versions of clang?

see https://github.com/rdf4cpp/rdf4cpp/runs/6956113826?check_suite_focus=true#step:9:34

2022-06-27 07:55 UTC, nkaralis requested changes

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_NegativeInteger.cpp
> +    CHECK_THROWS_WITH_AS(no_discard_dummy = Literal("0", type_iri), "XSD Parsing Error", std::runtime_error);
You could also add a test involving a positive number (>0).

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/UnsignedByte.hpp
> +    using cpp_datatype = u_int8_t;
uint8_t

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/UnsignedByte.hpp
> +    int conv_val = u_int16_t(value);
uint16_t

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/NonNegativeInteger.hpp
> +    using cpp_datatype = int64_t;
Shouldn't this be uint64_t?

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/PositiveInteger.hpp
> +    using cpp_datatype = int64_t;
Shouldn't this be uint64_t?

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/UnsignedInt.hpp
> +    using cpp_datatype = u_int32_t;
uint32_t

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/UnsignedLong.hpp
> +    using cpp_datatype = u_int64_t;
uint64_t

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/UnsignedLong.hpp
> +        if (ulong_val < std::numeric_limits<u_int64_t>::min() || ulong_val > std::numeric_limits<u_int64_t>::max()) throw std::runtime_error("XSD Parsing Error");
uint64_t

2022-06-27 07:55 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/UnsignedShort.hpp
> +    using cpp_datatype = u_int16_t;
uint16_t

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_UnsignedByte.cpp
> +    u_int8_t value = 1;
uint8_t

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_UnsignedInt.cpp
> +    u_int32_t value = 1;
uint32_t

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_UnsignedShort.cpp
> +    CHECK(std::is_same_v<type, u_int16_t>);
uint16_t

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_UnsignedLong.cpp
> +    u_int64_t value = 1;
uint64_t

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_UnsignedLong.cpp
> +    value = std::numeric_limits<u_int64_t>::max();
uint64_t

2022-06-27 07:55 UTC, nkaralis commented on tests/datatype/tests_Int.cpp
> +    auto value = 1;
In some tests you define value using the keyword `auto`, whereas in other test cases you use the `cpp_type` of the datatype. Is there a reason for this?

2022-07-01 13:38 UTC, nkaralis approved these changes

2022-11-07 08:55 UTC, closed without merging