Supports IEEE Floating Point Number Datatypes
TortugaAttack/rdf4cpp pull request #34
Opened 2022-06-21 05:32 UTC by kaimal11

Implements xsd::Float and xsd::Double datatypes

2022-06-27 09:24 UTC, nkaralis requested changes

2022-06-27 09:24 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/Double.hpp
> +        return "INF";
We need to also handle -INF.

2022-06-27 09:24 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/Float.hpp
> +        return "INF";
As in Double.hpp, we need to also handle -INF.

2022-06-27 09:24 UTC, nkaralis commented on tests/datatype/tests_Double.cpp
> +    CHECK(isinf(lit10.value<datatypes::xsd::Double>()));
We need to also check for -INF

2022-07-11 11:51 UTC, bigerl commented
we should have another look at precision before we merge 💡

2022-11-07 08:55 UTC, closed without merging