Support for Time and Date Datatypes
TortugaAttack/rdf4cpp pull request #36
Opened 2022-06-30 07:34 UTC by kaimal11

includes date, time, dateTime, and dateTimeStamp datatypes

2022-06-30 15:11 UTC, nkaralis requested changes

2022-06-30 15:11 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/Date.hpp
> +        throw std::runtime_error("XSD Parsing Error");
The standard defines the "day-of-month values" constraint (e.g., April has 30 days, so 31 is not a valid value). We have implement this constraint here.

2022-06-30 15:11 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/Date.hpp
> +        strptime(s.data(), "%Y-%m-%d", &tm);
How do you deal with the timezone fragment (which is optionally provided)?

2022-06-30 15:11 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/Date.hpp
> +    std::strftime(str, 32, "%Y-%m-%d", std::localtime(&value));
We also have to consider how to treat the timezone fragment here.

2022-06-30 15:11 UTC, nkaralis commented on tests/datatype/tests_Date.cpp
> +    tm.tm_mday = 31;
You need to document why this is equal to July 1st.

2022-06-30 15:11 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/DateTime.hpp
> +inline LiteralDatatypeImpl<xsd_dateTime>::cpp_type LiteralDatatypeImpl<xsd_dateTime>::from_string(std::string_view s) {
As in Date, we need to deal with the "day-of-month values" constraint and the timezone fragment.

2022-06-30 15:11 UTC, nkaralis commented on tests/datatype/tests_DateTimeStamp.cpp
> +    tm.tm_zone = "CEST"; //timezone
Test with other timezones as well.

2022-06-30 15:11 UTC, nkaralis commented on src/rdf4cpp/rdf/datatypes/xsd/Time.hpp
> +        strptime(s.data(), "%H:%M:%S", &tm);
We need to handle the optional timezone fragment.

2022-06-30 15:11 UTC, nkaralis commented on tests/datatype/tests_Time.cpp
> +TEST_CASE("Datatype Time") {
We need to test the values '00:00:00' and '24:00:00'. According to the standard, the lexical mapping maps both representations to the same value.

2022-07-11 11:58 UTC, bigerl commented on tests/datatype/tests_Time.cpp
> +TEST_CASE("Datatype Time") {
not done yet

2023-11-13 14:53 UTC, liss-h commented
Superceeded by #179

2023-11-13 14:53 UTC, closed without merging