Fix: integer ops will now always return xsd:integer
TortugaAttack/rdf4cpp pull request #70
Opened 2022-09-19 12:03 UTC by Clueliss

Introduces a new capability called `NumericStub`, which makes the type behave like it was numeric, without actually implementing any numeric ops. It instead relies on it's `numeric_impl_type` to perform the actual calculations.

Example: `xsd:int` is now a numeric-stub that delegates to `xsd:integer`.

This is implemented by simply calculating the required subtype offset to the impl-type (at compiletime) and then
always starting the common-type-conversion search at that offset (when searching for numeric type conversions).

2022-09-19 12:10 UTC, liss-h commented on src/rdf4cpp/rdf/datatypes/registry/DatatypeRegistry.hpp
> +        return res.has_value() && (**res).has_value() ? &***res : nullptr;
I have a feeling that you are not going to like this, but the reason is that `res` has type `std::optional<std::optional<NumericOps> const *>` and it needs to become `NumericOps const *` to avoid a copy and still have a sensible return type.

Suggestions are of course appreciated :)

2022-09-19 13:13 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/DatatypeRegistry.hpp
> +        return res.has_value() && (**res).has_value() ? &***res : nullptr;
```cpp
if (res.has_value()){
   if (auto const res_value = res.value(); res_value->has_value()){
      return &res_value->value();
   }
}
return nullptr;
```

how about ↑ plus some doc strings why each of the `has_value()` calls could return false.

2022-09-22 07:56 UTC, bigerl requested changes
Looks good and, albeit I tend to repeat myself, great work. Code looks even after this additional feature quite clean and architecture is clear. 
A little detail: I like that `get_numerical_ops` returns now a pointer. I think here it makes the code easier understandable avoiding that you have both a pointer that might be a null pointer wrapped into an optional that might not have a value. Both modeling the same thing. I can imagine that the  rusty part of your heart was bleeding a bit :)

2022-09-22 07:56 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/LiteralDatatype.hpp
> +concept NumericLiteralDatatype = LiteralDatatype<LiteralDatatypeImpl> && (NumericImpl<LiteralDatatypeImpl> || NumericStub<LiteralDatatypeImpl>);
doc

2022-09-22 07:56 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/LiteralDatatype.hpp
>  concept LogicalLiteralDatatype = LiteralDatatype<LiteralDatatypeImpl> && requires(typename LiteralDatatypeImpl::cpp_type const &value) {
doc

2022-09-22 07:56 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/DatatypeRegistry.hpp
> +    struct NumericOps : std::variant<NumericOpsStub, NumericOpsImpl> {
```suggestion
    struct NumericOps : public std::variant<NumericOpsStub, NumericOpsImpl> {
```

It's just for readability. But I had to look up if parent classes of structs are public by default.

2022-09-22 07:56 UTC, bigerl commented on src/rdf4cpp/rdf/datatypes/registry/DatatypeRegistry.hpp
>       * @return if available a structure containing function pointers for all numeric ops
```suggestion
     * @return if available a pointer to a structure containing function pointers for all numeric ops; otherwise a null pointer
```

2022-09-26 13:36 UTC, bigerl approved these changes

2022-09-26 13:37 UTC, merged